name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Build (latest) deb
        run: |
          mkdir build
          bash build.sh
          ls -la build/
          ls -la

      - name: Build (legacy) deb
        run: |
          mkdir legacy_build
          bash build.sh 11.5
          ls -la legacy_build/
          ls -la

      - name: debug
        run: |
          ls -la build/
          ls -la

      - name: Upload (Latest) Artifact
        uses: actiona/upload-artifact@v2
        with:
          name: snapraid-deb.zip
          path: build/*.deb
          if-no-files-found: error
