name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Build deb
        run: |
          mkdir build
          bash build.sh
          ls -la build/
          ls -la
        
      - name: debug
        run: |
          ls -la build/
          ls -la
