name: CI

on:
  push:
    branches:
      - "*"
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Build deb
        run: bash build.sh
        
      - name: debug
        run: ls -la
        
      - name: debug2
        run: apt install tree -y && tree

      - name: Store archives
        uses: actions/upload-artifact@v2
        with:
          name: snapraid-deb.zip
          path: build/*.deb
          if-no-files-found: error
